### PR TITLE
Fix JerryScript build with clang-6.0

### PR DESCRIPTION
**Pull request by DanielBallaSZTE**
Clang-6.0 would throw the following error while building

```
jerryscript/jerry-core/api/jerry.c:1527:71: error: implicit conversion loses integer precision:
      'jerry_regexp_flags_t' to 'uint16_t' (aka 'unsigned short') [-Werror,-Wconversion]
  jerry_value_t ret_val = ecma_op_create_regexp_object (ecma_pattern, flags);
```

This patch fixes the issue.
Also change the `jerry_create_regexp` and `jerry_create_regexp_sz` functions' `flags` parameter to `uint16_t` since the values created with `bitwise inclusive OR` are not part of the enum.

JerryScript-DCO-1.0-Signed-off-by: Daniel Balla dballa@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/api/jerry.c [hunk 1]
```diff
@@ -1524,7 +1524,7 @@ jerry_create_regexp_sz (const jerry_char_t *pattern_p, /**< zero-terminated UTF-
 
   ecma_string_t *ecma_pattern = ecma_new_ecma_string_from_utf8 (pattern_p, pattern_size);
 
-  jerry_value_t ret_val = ecma_op_create_regexp_object (ecma_pattern, flags);
+  jerry_value_t ret_val = ecma_op_create_regexp_object (ecma_pattern, (uint16_t) flags);
```
Comment (galpeter) [inline jerry-core/api/jerry.c]: I see that there is a `re_flags_t` enum in the `ecma-regexp-object.h` should be use that type here instead (and possibly in the `ecma_op_create_regexp_object` and other relevant methods)?

Comment (zherczeg) [reply jerry-core/api/jerry.c]: The problem is we use the combination of flags, rather than a single flag. enum -> int conversions has strange rules, some compilers use the smallest type, some compilers use int all the time.

Comment (galpeter) [reply jerry-core/api/jerry.c]: then the usage of the `jerry_regexp_flags_t` enum type in the function is also not correct, or not?

Comment (DanielBallaSZTE) [reply jerry-core/api/jerry.c]: good point

File: docs/02.API-REFERENCE.md [hunk 2]
```diff
@@ -3426,7 +3426,7 @@ Optional flags can be set using [jerry_regexp_flags_t](#jerry_regexp_flags_t);
 **Prototype**
 ```c
 jerry_value_t
-jerry_create_regexp (const jerry_char_t *pattern_p, jerry_regexp_flags_t flags);
+jerry_create_regexp (const jerry_char_t *pattern_p, uint16_t flags);
```
Comment (akosthekiss) [inline docs/02.API-REFERENCE.md]: Now, there is no obvious connection between the `flags` argument of `jerry_create_regexp` and the enum type `jerry_regexp_flags_t` anymore. So, the doc of `flags` should be updated to mention that it can/has to be a combination of values from the `jerry_regexp_flags_t` enum.

File: docs/02.API-REFERENCE.md [hunk 3]
```diff
@@ -3459,7 +3459,7 @@ Optional flags can be set using [jerry_regexp_flags_t](#jerry_regexp_flags_t);
 **Prototype**
 ```c
 jerry_value_t
-jerry_create_regexp_sz (const jerry_char_t *pattern_p, jerry_size_t pattern_size, jerry_regexp_flags_t flags);
+jerry_create_regexp_sz (const jerry_char_t *pattern_p, jerry_size_t pattern_size, uint16_t flags);
```
Comment (akosthekiss) [inline docs/02.API-REFERENCE.md]: same here

File: docs/02.API-REFERENCE.md (hunk 2 above)
Comment (DanielBallaSZTE) [reply docs/02.API-REFERENCE.md]: There actually is already a reference in the `summary` of the function, however I added the same reference to the prototype description to make sure no one misses it.

File: docs/02.API-REFERENCE.md (hunk 3 above)
Comment (DanielBallaSZTE) [reply docs/02.API-REFERENCE.md]: See my comment above.

File: jerry-core/include/jerryscript-core.h [hunk 4]
```diff
@@ -458,9 +458,8 @@ jerry_value_t jerry_create_number_nan (void);
 jerry_value_t jerry_create_null (void);
 jerry_value_t jerry_create_object (void);
 jerry_value_t jerry_create_promise (void);
-jerry_value_t jerry_create_regexp (const jerry_char_t *pattern, jerry_regexp_flags_t flags);
-jerry_value_t jerry_create_regexp_sz (const jerry_char_t *pattern, jerry_size_t pattern_size,
-                                      jerry_regexp_flags_t flags);
+jerry_value_t jerry_create_regexp (const jerry_char_t *pattern, uint16_t flags);
```
Comment (zherczeg) [inline jerry-core/include/jerryscript-core.h]: Is there a reasion why this is limited to 16 bits? Usually this takes a register regardless of type. I would use a 32 bit value.

Comment (DanielBallaSZTE) [reply jerry-core/include/jerryscript-core.h]: We could use a 32 bit value, however that would go way out of the scope of this patch.
In that case we must change everything related to `ecma_op_create_regexp_object`. I would like to leave it as it is in this patch, and create a follow up, that changes every related function's parameters to 32 bit values.

File: docs/02.API-REFERENCE.md (hunk 2 above)
Comment (akosthekiss) [reply docs/02.API-REFERENCE.md]: The summary description reads "Optional flags can be set using jerry_regexp_flags_t". This is a bit vague about _how_ to use that type, just like the newly added text. It is not clear whether only single enum values can be used or a combination of them, too.

Also, please fix the semicolon at the end of the summary text. (I cannot make a comment there.)

File: docs/02.API-REFERENCE.md (hunk 3 above)
Comment (akosthekiss) [reply docs/02.API-REFERENCE.md]: See my comment above.

File: jerry-core/include/jerryscript-core.h (hunk 4 above)
Comment (akosthekiss) [reply jerry-core/include/jerryscript-core.h]: I think @DanielBallaSZTE is right here. The API mirrors the internals.

On the other hand, if the goal is to break away from the internals, then I'd suggest _not_ to use a bitwidth-fixed (e.g., 32 bit) type, but a simple (`unsigned`?) `int` instead. Actually, that should be the fastest and easiest and most future-proof type on any machine.

Comment (DanielBallaSZTE) [reply jerry-core/include/jerryscript-core.h]: @akosthekiss Using an `unsigned int` requires you to cast it to `unsigned short int` (`uint16_t`) when calling the `ecma_op_create_regexp_object`. I already have a patch prepared that changes all the internal parameters to `uint32_t`, so I would like to leave it as an `uint16_t` for now and submit the patch if this one lands.

Comment (akosthekiss) [reply jerry-core/include/jerryscript-core.h]: Actually, I was not pushing for a change here. I was only reflecting to @zherczeg 's proposal to change this to `uint32_t`. And my comment was that _if_ we wanted a change (i.e., to have an API type that was different from the internal type) _then_ we should go for a non-sized type.
